ATS75/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views as myview

app_name="ATS75"
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="ATS75/login.html"), name='login'),
    path('logout/' , auth_views.logout_then_login , name='logout'),
    path('signup/' , myview.signup , name='signup' ),
    #
    path('', myview.home , name='home'),
    #
    path('addschedule/' , myview.add_schedule , name='add_schedule' ),
    #
    path('deleteschedule/', myview.delete_schedule , name='delete_schedule'),
    #
    path('addsubject/', myview.add_subject , name='add_subject'),
    #
    path('myattendancerecord/' , myview.show_attendance_record , name='show_attendance_record')
]

projects/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('ATS75.urls')),
]

ATS75/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.

class Student(models.Model):
    student=models.OneToOneField(User,on_delete=models.CASCADE)
    student_institution=models.CharField(max_length=100)
    schedule_start_date=models.DateField(null=True,blank=True)
    schedule_end_date=models.DateField(null=True,blank=True)
    threshold=models.FloatField(null=True,blank=True)

    def __str__(self):
        return str(self.student.username)+" : "+str(self.student_institution) # pylint: disable=no-member


class Subject(models.Model):
    subject_code=models.CharField(max_length=10)
    subject_name=models.CharField(max_length=50)
    teacher_name=models.CharField(max_length=50)

    # user_ref: to know who owns this subject
    user_ref=models.ForeignKey(Student,on_delete=models.CASCADE)

    class Meta:
        unique_together=(("user_ref","subject_code"),)

    def __str__(self):
        return str(self.user_ref.student.username)+" : "+str(self.subject_code)+':'+str(self.subject_name) #pylint: disable=no-member



class TTCell(models.Model):
    #Row of TT
    day=models.CharField(max_length=3)
    #Column of TT
    time_slot_start=models.TimeField()
    time_slot_end=models.TimeField()
    #value
    subject=models.ForeignKey(Subject,on_delete=models.CASCADE,null=True)

    # user_ref: to know who owns this cell as we are making TT with cells that points to user
    user_ref=models.ForeignKey(Student,on_delete=models.CASCADE)

    class Meta:
        unique_together=(("user_ref","day","time_slot_start"),)

    def __str__(self):
        return str(self.user_ref.student.username)+" : "+str(self.day)+" : "+str(self.time_slot_start)+"-"+str(self.time_slot_end) #pylint:disable=no-member



class ARCell(models.Model):
    #Row of Attendence Record
    date=models.DateField()
    #Column of Attendence Record
    time_slot_start=models.TimeField()
    time_slot_end=models.TimeField()
    #value
    value=models.CharField(max_length=2)

    #user_ref:
    user_ref=models.ForeignKey(Student,on_delete=models.CASCADE)

    class Meta:
        unique_together=(("user_ref","date","time_slot_start"),)

    def __str__(self):
        return str(self.user_ref.student.username)+" : "+str(self.date)+" : "+str(self.time_slot_start)+"-"+str(self.time_slot_end) #pylint:disable=no-member

ATS75/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class DateInput(forms.DateInput):
    input_type='date'

class AddScheduleForm(forms.Form):
    start_date=forms.DateField(required=True,widget=DateInput)
    end_date=forms.DateField(required=True,widget=DateInput)
    percentage_criteria=forms.FloatField(required=True)

class AddSubjectForm(forms.Form):
    subject_code=forms.CharField(max_length=10,required=True)
    subject_name=forms.CharField(max_length=50,required=True)
    teacher_name=forms.CharField(max_length=50,required=True)

class SignUpForm(UserCreationForm):
    institution=forms.CharField(max_length=100,required=True)
    first_name=forms.CharField(max_length=30,required=True)
    last_name=forms.CharField(max_length=30,required=True)
    email=forms.EmailField(required=True)

    class Meta:
        model=User
        fields=(
            'username',
            'first_name',
            'last_name',
            'email',
            'institution',
            'password1',
            'password2',
        )

ATS75/views.py
from django.shortcuts import render , reverse

from django.http import HttpResponse,HttpResponseRedirect

from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login
from django.db import IntegrityError

from django.utils import timezone

from .models import Student

from . import forms

# Create your views here.

daysofweek=['Mon','Tue','Wed','Thu','Fri','Sat','Sun']
availableslots=['08:00 - 09:00','09:00 - 10:00','10:00 - 11:00','11:00 - 12:00','12:00 - 13:00',
                '13:00 - 14:00','14:00 - 15:00','15:00 - 16:00','16:00 - 17:00','17:00 - 18:00']

def signup(request):
    
    if request.method == 'POST':
        form=forms.SignUpForm(request.POST)
        if form.is_valid():

            user=form.save()
            newstudent=Student(student=user,student_institution=form.cleaned_data['institution'])
            newstudent.save()
            user=authenticate(username=user.username,password=form.cleaned_data['password1'])
            login(request,user)
            return HttpResponseRedirect(reverse('ATS75:home'))

    else:
        form=forms.SignUpForm()
    
    return render( request , 'ATS75/signup.html' , {'form':form} )

@login_required
def home(request):
    user=Student.objects.get(student=request.user)
    timetable=user.ttcell_set.all()
    context={'user':user , 'daysofweek':daysofweek , 'availableslots':availableslots , 'timetable':timetable}
    return render(request , 'ATS75/home.html' , context) 

@login_required
def add_schedule(request):

    user=Student.objects.get(student=request.user)
    if request.method == 'POST':
        form=forms.AddScheduleForm(request.POST)
        if form.is_valid():
            
            user.schedule_start_date=request.POST['start_date']
            user.schedule_end_date=request.POST['end_date']
            user.threshold=request.POST['percentage_criteria']
            for cell in user.arcell_set.all():
                cell.delete()
            for cell in user.ttcell_set.all():
                cell.delete()
            for days in daysofweek:
                for slots in availableslots:
                    id="subject_"+days+"_"+slots
                    timetableentry=request.POST[id]
                    if timetableentry!="":
                        subject=user.subject_set.get(pk=timetableentry)
                        user.ttcell_set.create(
                            day=days,
                            time_slot_start=slots[:5],
                            time_slot_end=slots[-5:],
                            subject=subject,
                            user_ref=user
                        )
            user.save()

            return HttpResponseRedirect(reverse('ATS75:home'))
    else:
        if user.subject_set.count()==0:
            return HttpResponseRedirect(reverse('ATS75:add_subject'))
        form=forms.AddScheduleForm()
    
    context={
        'form':form,
        'daysofweek':daysofweek,
        'availableslots':availableslots,
        'user':user
    }
    return render( request , 'ATS75/addschedule.html', context )


@login_required
def delete_schedule(request):

    user=Student.objects.get(student=request.user)
    for data in user.arcell_set.all():
        data.delete()
    for data in user.ttcell_set.all():
        data.delete()
    for data in user.subject_set.all():
        data.delete()
    user.schedule_start_date=None
    user.schedule_end_date=None
    #user.threshold=None
    user.save()

    return HttpResponseRedirect(reverse('ATS75:home'))


@login_required
def add_subject(request):

    error_message=None

    if request.method == 'POST':
        form=forms.AddSubjectForm(request.POST)
        if form.is_valid():
            user=Student.objects.get(student=request.user)
            try:
                user.subject_set.create(
                    subject_code=form.cleaned_data['subject_code'],
                    subject_name=form.cleaned_data['subject_name'],
                    teacher_name=form.cleaned_data['teacher_name'],
                    user_ref=user
                )
                user.save()
            except (IntegrityError):
                error_message="Subject Already Exist !!. Please Check the subject code and name."
            else:
                if request.POST['addanother']=="0":
                    return HttpResponseRedirect(reverse('ATS75:add_schedule'))
                else:
                    form=forms.AddSubjectForm()
    else:
        form=forms.AddSubjectForm()
    
    return render(request , 'ATS75/addsubject.html' , {'form':form , 'error_message':error_message} )



@login_required
def show_attendance_record(request):

    user=Student.objects.get(student=request.user)
    start_date=user.schedule_start_date
    end_date=user.schedule_end_date
    todays_date=timezone.now().date()

    datesrange=[]

    # for subject wise report
    subjectreport=[] # subject,total,present,percentage,absent-left
    subjectindex={}
    timetable=user.ttcell_set.all()
    att_record=user.arcell_set.all()
    threshold=user.threshold
    days_left=[]
    days_till_curr_date=[]

    for subject in user.subject_set.all():
        subjectindex[subject]=len(subjectreport)
        subjectreport.append([ subject , 0 , 0 , 0 , 0])
        days_left.append(0)
        days_till_curr_date.append(0)

    curr_date=start_date
    while curr_date<=end_date:

        curr_day=daysofweek[curr_date.weekday()]
        cells=timetable.filter(day=curr_day)
        for cell in cells:
            idx=subjectindex[cell.subject]
            
            if curr_date<=todays_date:
                data=att_record.filter(date=curr_date,time_slot_start=cell.time_slot_start)
                subjectreport[idx][1]+=1
                days_till_curr_date[idx]+=1
                if data.count()!=0:
                    if data[0].value=='1':
                        subjectreport[idx][2]+=1
                    elif data[0].value!='0':
                        subjectreport[idx][1]-=1
                        days_till_curr_date[idx]-=1
            else:
                subjectreport[idx][1]+=1
                days_left[idx]+=1

        if curr_date<=todays_date:
            datesrange.append(curr_date)
        curr_date=curr_date+timezone.timedelta(1)
    
    for i in range(len(subjectreport)):
        row=subjectreport[i]
        row[0]=row[0].subject_code+" : "+row[0].subject_name
        if days_till_curr_date[i]!=0:
            row[3]=row[2]*100/days_till_curr_date[i]
        row[4]=row[2]+days_left[i]-(threshold*row[1])/100
        subjectreport[i]=row
        if row[4]<0:
            row[4]="You can't make it now."
        else:
            row[4]=int(row[4])
    
    context={
        'user': user,
        'datesrange': datesrange,
        'daysofweek': daysofweek,
        'availableslots': availableslots,

        # for subject wise report
        'subjectreport': subjectreport
    }

    if request.method == 'POST':
        day=request.POST['day']
        date=request.POST[day+'_date']
        userardata=user.arcell_set.filter(date=date)
        for cell in userardata:
            cell.delete()
        for cell in user.ttcell_set.all():
            if cell.day == day:
                val=None
                if day+"_GH" in request.POST:
                    val="GH"
                elif day+"_"+str(cell.time_slot_start) not in request.POST:
                    val="0"
                else:
                    val=request.POST[day+"_"+str(cell.time_slot_start)]

                user.arcell_set.create(
                    date=date,
                    time_slot_start=cell.time_slot_start,
                    time_slot_end=cell.time_slot_end,
                    value=val,
                    user_ref=user
                )
        return HttpResponseRedirect(reverse('ATS75:show_attendance_record'))
        

    return render( request , 'ATS75/showattendancerecord.html' , context )


"""
subject total present percentage absents-left

"""

ATS75/templates/ATS75/addschedule.html
{% extends 'ATS75/base.html' %}
{% block content %}

<h2>Add Schedule</h2>

<style>
select {
    border: none;
    outline: none;
    scroll-behavior: smooth;
    padding: 10px;
}

option{
    font-size: medium;
}
</style>

<div class="row" style="padding: 1%;">
    <div class="col-sm-12">
        <a href="{% url 'ATS75:add_subject' %}" class="btn btn-info" role="button">Add more subjects</a>
    </div>
</div>
<br>

<form action="{% url 'ATS75:add_schedule' %}" method="post" onsubmit="return validate()">

    {% csrf_token %}
    {{form.as_p}}

    <div class="table-responsive">
    <table class="table table-striped table-hover" align="center" id="timetable">

        <tr>
            <th> --- </th>
            {% for slots in availableslots %}
                <th style="text-align: center;"> {{slots}} </th>
            {% endfor %}
        </tr>

        {% for days in daysofweek %}
            <tr>
                <th> {{days}} </th>
                {% for slots in availableslots %}
                    <td>

                        <select name="subject_{{days}}_{{slots}}" id="subject_{{days}}_{{slots}}">
                            <option value="" selected></option>
                            {% for subject in user.subject_set.all %}
                                <option value="{{subject.pk}}">{{subject.subject_code}}:{{subject.subject_name}}</option>
                            {% endfor %}
                        </select>

                    </td>
                {% endfor %}
            </tr>
        {% endfor %}

        <!-- script for selecting the previous selected value if any -->
        <script>
            {% for cell in user.ttcell_set.all %}
                var id="subject_{{cell.day}}_{{cell.time_slot_start|time:'H:i'}} - {{cell.time_slot_end|time:'H:i'}}";
                document.getElementById(id).value="{{cell.subject.pk}}";
            {% endfor %}
            document.getElementById("id_start_date").value="{{user.schedule_start_date.isoformat}}";
            document.getElementById("id_end_date").value="{{user.schedule_end_date.isoformat}}";
            document.getElementById("id_percentage_criteria").value="{{user.threshold}}";
        </script>

    </table>
    </div>

    <div class="row">
        <div class="col-sm-12" style="padding: 1%; text-align: center;">
            <input class="btn btn-success btn-lg" type="submit" value="Submit">
        </div>
    </div>

</form>

<script>
    function validate(){

        var daysofweek=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
        var availableslots=['08:00 - 09:00','09:00 - 10:00','10:00 - 11:00','11:00 - 12:00','12:00 - 13:00',
                            '13:00 - 14:00','14:00 - 15:00','15:00 - 16:00','16:00 - 17:00','17:00 - 18:00'];

        var table = document.getElementById("timetable");
        var empty=1;
        
        for(var i=0 ; i<daysofweek.length ; i++){
            for(var j=0 ; j<availableslots.length ; j++){
                var id="subject_"+daysofweek[i]+"_"+availableslots[j];
                cell=document.getElementById(id);
                if(cell.value!=""){
                    empty=0;
                }
            }
        }
        error_text="";
        var startdate=document.getElementById("id_start_date").value;
        var enddate=document.getElementById("id_end_date").value;
        if(startdate>=enddate){
            error_text+="Please enter correct dates, start date should be less than end date !!! \n\n";
        }
        if(empty==1){
            error_text+="Please enter some subjects in your timetable !!!\n";
        }
        if(error_text!=""){
            alert(error_text);
            return false;
        }
        return true;
    }
</script>

{% endblock %}

ATS75/templates/ATS75/addsubject.html
{% extends 'ATS75/base.html' %}
{% block content %}

<h2>Add Subject</h2>

<div class="container">

<h4>Add some subjects to create a timetable</h4>

{% if error_message %}
    <p style="color: red; font-weight: bold;">{{error_message}}</p>
{% endif %}

<form action="{% url 'ATS75:add_subject' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="text" style="display: none;" id="addanother" name="addanother" value="0">
    <input class="btn btn-success" type="submit" value="Save">
    <input class="btn btn-success" type="submit" value="Save and Add Another" onclick="addanotherfunction()">
</form>

</div>

<script>
    function addanotherfunction(){
        document.getElementById("addanother").value="1"
    }
</script>

{% endblock %}

ATS75/templates/ATS75/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        h1,h2{
            text-align: center;
            font-weight: bold;
        }
        .heading{
            /*background-image: url('https://image.shutterstock.com/image-vector/man-hold-attendance-clipboard-checklist-260nw-1181636773.jpg');*/
            background-image: url('https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT57g3q12pT7RN35jSh641zW-ZKzeHJrKZKkAkEmX6ulsgZrO9-');
            background-repeat: no-repeat;
            /*background-color: rgb(55, 206, 185);*/
            background-color: rgb(138, 190, 203);
        }
    </style>
</head>
<body>
<div class="container-fluid">

<div class="jumbotron heading">
    <h1>Attendance Tracking System</h1>
</div> <!--this also creates a hr line below it-->


{% block content %}
{% endblock %}


<hr>

<div class="row">
    <div class="col-sm-6" style="text-align: center; padding: 1%;">
        <a href="{% url 'ATS75:home' %}" class="btn btn-info" role="button">Home Page</a>
    </div>
    <div class="col-sm-6" style="text-align: center; padding: 1%;">
        <a href="{% url 'ATS75:logout' %}" class="btn btn-danger" role="button">Logout</a>
    </div>
</div>
<hr>

</div>
</body>
</html>

ATS75/templates/ATS75/home.html
{% extends 'ATS75/base.html' %}
{% block content %}

<h2>Welcome</h2>
<h4 style="font-weight: bold; text-align: right;padding-right: 5%;">Institute : {{user.student_institution}}</h4>

<p><b> Hello {{user.student.username}} !! Please stay at home_/\_ </b></p>

<p><b>A Motivational Quote:</b></p>

{% if user.ttcell_set.count == 0 %}

    <br>
    <p>No Schedule Yet</p>
    <br>
    <a href="{% url 'ATS75:add_schedule' %}" class="btn btn-info" role="button">Add one..</a>


{% else %}

    <hr>
    <b>Schedule :</b> from {{user.schedule_start_date}} to {{user.schedule_end_date}}

    <br>
    <h2>Time Table</h2>

    <div class="table-responsive">
    <table class="table table-striped table-bordered" align="center">

        <tr>
            <th> --- </th>
            {% for slots in availableslots %}
                <th style="text-align: center;"> {{slots}} </th>
            {% endfor %}
        </tr>

        {% for days in daysofweek %}
            <tr>
                <th> {{days}} </th>
                {% for slots in availableslots %}
                    <td style="text-align: center;">
                        {% for cell in timetable %}
                            {% if cell.day == days and cell.time_slot_start|time:"H:i" == slots|slice:":5" %}
                                {{cell.subject.subject_code}}<br>{{cell.subject.subject_name}}
                            {% endif %}
                        {% endfor %}
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}

    </table>
    </div>

    <hr>
    <div class="row">
    <div class="col-sm-4" style="text-align: center; padding: 1%;">
    <a href="{% url 'ATS75:show_attendance_record' %}" class="btn btn-info" role="button">My Attendance Record</a>
    </div>
    <div class="col-sm-4" style="text-align: center; padding: 1%;">
    <button class="btn btn-info" onclick="confirm_update_function()">Update this schedule</a>
    </div>
    <div class="col-sm-4" style="text-align: center; padding: 1%;">
    <button class="btn btn-danger" onclick="confirm_delete_function()" >Delete this schedule</a>
    </div>
    </div>

{% endif %}

<!--Model for confirm dialog box-->

<div class="container">
    <div class="modal fade" id="confirms-update" role="dialog" style="padding: 10%;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <p>This will delete your current Attendance Record on updating the timetable (not adding a subject).<br>Sure you want to update it?</p>
                </div>
                <div class="modal-footer">
                    <a href="{% url 'ATS75:add_schedule' %}" class="btn btn-success" role="button">YES</a>
                    <button class="btn btn-warning" type="button" data-dismiss="modal">NO</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="modal fade" id="confirms-delete" role="dialog" style="padding: 10%;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <p>All the Subjects + Timetable + Attendance Record will be deleted.<br> Sure you want to delete it?</p>
                </div>
                <div class="modal-footer">
                    <a href="{% url 'ATS75:delete_schedule' %}" class="btn btn-success" role="button">YES</a>
                    <button class="btn btn-warning" type="button" data-dismiss="modal">NO</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function confirm_delete_function(){
        $("#confirms-delete").modal();
    }

    function confirm_update_function(){
        $("#confirms-update").modal();
    }
</script>

{% endblock %}

ATS75/templates/ATS75/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        h1,h2{
            text-align: center;
            font-weight: bold;
        }
        .heading{
            /*background-image: url('https://image.shutterstock.com/image-vector/man-hold-attendance-clipboard-checklist-260nw-1181636773.jpg');*/
            background-image: url('https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT57g3q12pT7RN35jSh641zW-ZKzeHJrKZKkAkEmX6ulsgZrO9-');
            background-repeat: no-repeat;
            /*background-color: rgb(55, 206, 185);*/
            background-color: rgb(138, 190, 203);
        }
    </style>
</head>
<body>
<div class="container-fluid">

<div class="jumbotron heading">
    <h1>Attendance Tracking System</h1>
</div> <!--this also creates a hr line below it-->


<div class="container">

<h2> Login </h2>

<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Login" class="btn btn-success btn-lg">
</form>

<div class="row">
<div class="col-sm-12" style="text-align: center; padding: 1%;">
<a href="{% url 'ATS75:signup' %}" class="btn btn-info" role="button"> New Member? Sign Up now</a>
</div>
</div>

</div>

<hr>

</div>
</body>
</html>

ATS75/templates/ATS75/showattendancerecord.html
{% extends "ATS75/base.html" %}
{% block content %}

{% for days in daysofweek %}
    
<div class="container">
    <div class="modal fade" id="{{days}}" role="dialog" style="padding: 10%;">
        <div class="modal-dialog">

            <div class="modal-content">
                <div class="modal-body">

        <form action="{% url 'ATS75:show_attendance_record' %}" method="POST">
        {% csrf_token %}

            <input type="text" name="day" value="{{days}}" style="display: none;">
            <input type="text" id="{{days}}_date" name="{{days}}_date" style="display: none;">

            <input type="checkbox" name="{{days}}_GH" id="{{days}}_GH" value="1">
            <label for="{{days}}_GH">That day is a Gazetted Holiday</label><br><br>

            <ul class="list-group">
            {% for cell in user.ttcell_set.all %}
                {% if cell.day == days %}
                    <li class="list-group-item">
                    <p>Did you attended {{cell.subject.subject_name}} at {{cell.time_slot_start}}??</p>
                    <input type="radio" id="{{days}}_{{cell.time_slot_start}}_1" name="{{days}}_{{cell.time_slot_start.isoformat}}" value="1">
                    <label for="{{days}}_{{cell.time_slot_start}}_1">Present</label><br>

                    <input type="radio" id="{{days}}_{{cell.time_slot_start}}_0" name="{{days}}_{{cell.time_slot_start.isoformat}}" value="0">
                    <label for="{{days}}_{{cell.time_slot_start}}_0">Absent</label><br>

                    <input type="radio" id="{{days}}_{{cell.time_slot_start}}_TL" name="{{days}}_{{cell.time_slot_start.isoformat}}" value="TL">
                    <label for="{{days}}_{{cell.time_slot_start}}_TL">Teacher On Leave</label><br>

                    <input type="radio" id="{{days}}_{{cell.time_slot_start}}_CS" name="{{days}}_{{cell.time_slot_start.isoformat}}" value="CS">
                    <label for="{{days}}_{{cell.time_slot_start}}_CS">Class Suspended</label><br>

                    </li>

                {% endif %}
            {% endfor %}
            </ul>
            <input class="btn btn-success" type="submit" value="OK">
        </form>

                </div>
            </div>
        </div>
    </div>
</div>

{% endfor %}

<h1 style="text-align: center;">Subject Wise Report</h1>

<div class="table-responsive">
<table class="table table-striped table-hover" align="center">
    <tr>
        <th>Subject</th><th>Total Classes</th><th>Present</th><th>Precentage</th><th>Absents You Can Take</th>
    </tr>
    {% for row in subjectreport %}
        <tr>
            {% for data in row %}
                {% if forloop.counter0 == 3 %}
                    <td>{{data|floatformat:2}}%</td>
                
                {% else %}
                    <td>{{data}}</td>
                {% endif %}
            {% endfor %}
        </tr>
    {% endfor %}
</table>
</div>

<hr>

<h1 style="text-align: center;" >My Attendance Record</h1>

<div class="table-responsive">
<table class="table table-striped table-hover" >
    <tr>
        <th>---</th>
        {% for slots in availableslots %}
            <th>{{slots}}</th>
        {% endfor %}
    </tr>

    {% for date in datesrange %}
        <tr>
            <th onclick="addrecord(this);" id="{{date|date:'Y-m-d'}}" role="button">{{date|date:'M j, Y (D)'}}</th>
            {% for slots in availableslots %}
                <td id="cell_{{date}}_{{slots}}" align="center"></td>
            {% endfor %}
        </tr>
    {% endfor %}

    <!--script for filling record in cell-->
    <script>
        {% for cell in user.arcell_set.all %}
            var id="cell_{{cell.date}}_{{cell.time_slot_start|time:'H:i'}} - {{cell.time_slot_end|time:'H:i'}}";
            document.getElementById(id).innerHTML="{{cell.value}}";
        {% endfor %}
    </script>

</table>
</div>

<p style="text-align: center; color: red; font-weight: bold;">*Click on the date to update attendance record for that date.</p>

<script>
    function addrecord(ele){
        var value=ele.innerHTML;
        var len=value.length;
        var day=value[len-4]+value[len-3]+value[len-2];
        var count=0;
        document.getElementById(day+"_date").value=ele.id;
        $("#"+day).modal();
    }
</script>

{% endblock %}

ATS75/templates/ATS75/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        h1,h2{
            text-align: center;
            font-weight: bold;
        }
        .heading{
            /*background-image: url('https://image.shutterstock.com/image-vector/man-hold-attendance-clipboard-checklist-260nw-1181636773.jpg');*/
            background-image: url('https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT57g3q12pT7RN35jSh641zW-ZKzeHJrKZKkAkEmX6ulsgZrO9-');
            background-repeat: no-repeat;
            /*background-color: rgb(55, 206, 185);*/
            background-color: rgb(138, 190, 203);
        }
    </style>
</head>
<body>
<div class="container-fluid">

<div class="jumbotron heading">
    <h1>Attendance Tracking System</h1>
</div> <!--this also creates a hr line below it-->

<div class="container">

    <h2> Sign Up </h2>

    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Sign Up" class="btn btn-success btn-lg">
    </form>


    <div class="row">
    <div class="col-sm-12" style="padding: 1%; text-align: center;">
    <a href="{% url 'ATS75:login' %}" class="btn btn-info" role="button"> Already have an account? Login now </a>
    </div>
    </div>

</div>

<hr>

</div>
</body>
</html>